begin remote
  name  DAIKIN_ARC433
  bits            8
  flags SPACE_ENC
  eps             30
  aeps          100
  header       9300 4500
  one           520 1700
  zero          520 520
  gap          45000
  frequency      38000
  begin codes
      KEY_POWER       0x01
      KEY_TEMPUP      0x02
      KEY_TEMPDOWN    0x03
      KEY_MODE_COOL   0x04
      KEY_MODE_HEAT   0x05
      KEY_MODE_DRY    0x06
      KEY_MODE_FAN    0x07
      KEY_FAN_AUTO    0x08
      KEY_FAN_LOW     0x09
      KEY_FAN_MED     0x0A
      KEY_FAN_HIGH    0x0B
      KEY_SWING_ON    0x0C
      KEY_SWING_OFF   0x0D
      KEY_SLEEP       0x0E
      KEY_TURBO       0x0F
  end codes
end remote
