begin remote
  name  SAMSUNG_BN59-00941A
  bits            16
  flags SPACE_ENC|CONST_LENGTH
  eps             30
  aeps          100
  header       4500 4500
  one           560 1690
  zero          560 560
  pre_data_bits   16
  pre_data       0xE0E0
  post_data_bits  16
  post_data      0xFFFF
  gap          45000
  repeat_bit     0
  frequency      38000
  begin codes
      KEY_POWER       0x40BF
      KEY_VOLUMEUP    0x609F
      KEY_VOLUMEDOWN  0xA05F
      KEY_CHANNELUP   0x20DF
      KEY_CHANNELDOWN 0xE01F
      KEY_MUTE        0x906F
      KEY_MENU        0x50AF
      KEY_OK          0x10EF
      KEY_UP          0x8877
      KEY_DOWN        0x9867
      KEY_LEFT        0xA857
      KEY_RIGHT       0x48B7
      KEY_BACK        0x28D7
      KEY_EXIT        0x12ED
      KEY_SOURCE      0xD02F
      KEY_INFO        0x5AA5
      KEY_HOME        0x7A85
      KEY_GUIDE       0x1AE5
      KEY_ASPECT      0x0AF5
      KEY_SUBTITLE    0xE21D
      KEY_PICTURE     0x52AD
      KEY_SLEEP       0x9A65
      KEY_NETFLIX     0xE21D
      KEY_YOUTUBE     0x52AD
      KEY_PRIME       0x9A65
  end codes
end remote

begin remote
  name  LG_AKB75095304
  bits            16
  flags SPACE_ENC|CONST_LENGTH
  eps             30
  aeps          100
  header       9000 4500
  one           560 1690
  zero          560 560
  pre_data_bits   16
  pre_data       0x20DF
  gap          45000
  frequency      38000
  begin codes
      KEY_POWER       0x10EF
      KEY_VOLUMEUP    0x40BF
      KEY_VOLUMEDOWN  0xC03F
      KEY_CHANNELUP   0x00FF
      KEY_CHANNELDOWN 0x807F
      KEY_MUTE        0xD02F
      KEY_MENU        0x50AF
      KEY_OK          0x20DF
      KEY_UP          0x60BF
      KEY_DOWN        0xA05F
      KEY_LEFT        0xE01F
      KEY_RIGHT       0x906F
      KEY_BACK        0x48B7
      KEY_EXIT        0x7887
      KEY_SOURCE      0xB04F
      KEY_INFO        0x0AF5
      KEY_HOME        0x7A85
  end codes
end remote
