begin remote
  name  SONY_RM-ED044
  bits            12
  flags SPACE_ENC
  eps             30
  aeps          100
  header       2400 600
  one           600 1200
  zero          600 600
  gap          45000
  frequency      40000
  begin codes
      KEY_POWER       0x15
      KEY_VOLUMEUP    0x12
      KEY_VOLUMEDOWN  0x13
      KEY_CHANNELUP   0x10
      KEY_CHANNELDOWN 0x11
      KEY_MUTE        0x14
      KEY_MENU        0x18
      KEY_OK          0x1A
      KEY_UP          0x1B
      KEY_DOWN        0x1C
      KEY_LEFT        0x1D
      KEY_RIGHT       0x1E
      KEY_BACK        0x1F
      KEY_HOME        0x20
      KEY_INPUT       0x21
  end codes
end remote
